<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <Nullable>disable</Nullable>
    <UseUwp>true</UseUwp>
    <DefaultLanguage>en-US</DefaultLanguage>
    <IsAotCompatible>true</IsAotCompatible>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <RootNamespace>Telerik.UI.Xaml.Controls.Primitives</RootNamespace>
    <AssemblyName>Telerik.UI.Xaml.Primitives.UWP</AssemblyName>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\BuildTools\Win8PublicKey.snk</AssemblyOriginatorKeyFile>
    <Platforms>ARM64;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DefineConstants>$(DefineConstants);DEBUG;TRACE;NETFX_CORE;WINDOWS_UWP</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DefineConstants>$(DefineConstants);TRACE;NETFX_CORE;WINDOWS_UWP</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="PanAndZoomImage\**" />
    <Compile Remove="RadialMenu\Services\Actions\**" />
    <EmbeddedResource Remove="PanAndZoomImage\**" />
    <EmbeddedResource Remove="RadialMenu\Services\Actions\**" />
    <None Remove="PanAndZoomImage\**" />
    <None Remove="RadialMenu\Services\Actions\**" />
    <Page Remove="PanAndZoomImage\**" />
    <Page Remove="RadialMenu\Services\Actions\**" />
    <PRIResource Remove="PanAndZoomImage\**" />
    <PRIResource Remove="RadialMenu\Services\Actions\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Common\Services\Updates\UpdateFlags.cs" />
    <Compile Remove="HubTile\DoubleScaleConverter.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.203">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core.UWP\Core.UWP.csproj" />
  </ItemGroup>
</Project>
