<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <Nullable>disable</Nullable>
    <UseUwp>true</UseUwp>
    <DefaultLanguage>en-US</DefaultLanguage>
    <IsAotCompatible>true</IsAotCompatible>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <AssemblyName>Telerik.Core</AssemblyName>
    <RootNamespace>Telerik.Core</RootNamespace>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\BuildTools\Win8PublicKey.snk</AssemblyOriginatorKeyFile>
    <Platforms>ARM64;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DefineConstants>$(DefineConstants);DEBUG;TRACE;NETFX_CORE;WINDOWS_UWP</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DefineConstants>$(DefineConstants);TRACE;NETFX_CORE;WINDOWS_UWP</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Collections\**" />
    <EmbeddedResource Remove="Collections\**" />
    <None Remove="Collections\**" />
    <Page Remove="Collections\**" />
    <PRIResource Remove="Collections\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.203">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
