<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <Nullable>disable</Nullable>
    <UseUwp>true</UseUwp>
    <DefaultLanguage>en-US</DefaultLanguage>
    <IsAotCompatible>true</IsAotCompatible>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <RootNamespace>Telerik.UI.Xaml.Controls.Grid</RootNamespace>
    <AssemblyName>Telerik.UI.Xaml.Grid.UWP</AssemblyName>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\BuildTools\Win8PublicKey.snk</AssemblyOriginatorKeyFile>
    <Platforms>ARM64;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DefineConstants>$(DefineConstants);DEBUG;TRACE;NETFX_CORE;WINDOWS_UWP</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DefineConstants>$(DefineConstants);TRACE;NETFX_CORE;WINDOWS_UWP</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Assets\CheckBox\**" />
    <Compile Remove="Assets\DataOperationsControl\**" />
    <Compile Remove="Assets\Resize\**" />
    <Compile Remove="Data\**" />
    <Compile Remove="View\Descriptors\Aggregates\**" />
    <Compile Remove="View\Descriptors\Collections\**" />
    <Compile Remove="View\Descriptors\Filtering\DataEngineMapping\**" />
    <EmbeddedResource Remove="Assets\CheckBox\**" />
    <EmbeddedResource Remove="Assets\DataOperationsControl\**" />
    <EmbeddedResource Remove="Assets\Resize\**" />
    <EmbeddedResource Remove="Data\**" />
    <EmbeddedResource Remove="View\Descriptors\Aggregates\**" />
    <EmbeddedResource Remove="View\Descriptors\Collections\**" />
    <EmbeddedResource Remove="View\Descriptors\Filtering\DataEngineMapping\**" />
    <None Remove="Assets\CheckBox\**" />
    <None Remove="Assets\DataOperationsControl\**" />
    <None Remove="Assets\Resize\**" />
    <None Remove="Data\**" />
    <None Remove="View\Descriptors\Aggregates\**" />
    <None Remove="View\Descriptors\Collections\**" />
    <None Remove="View\Descriptors\Filtering\DataEngineMapping\**" />
    <Page Remove="Assets\CheckBox\**" />
    <Page Remove="Assets\DataOperationsControl\**" />
    <Page Remove="Assets\Resize\**" />
    <Page Remove="Data\**" />
    <Page Remove="View\Descriptors\Aggregates\**" />
    <Page Remove="View\Descriptors\Collections\**" />
    <Page Remove="View\Descriptors\Filtering\DataEngineMapping\**" />
    <PRIResource Remove="Assets\CheckBox\**" />
    <PRIResource Remove="Assets\DataOperationsControl\**" />
    <PRIResource Remove="Assets\Resize\**" />
    <PRIResource Remove="Data\**" />
    <PRIResource Remove="View\Descriptors\Aggregates\**" />
    <PRIResource Remove="View\Descriptors\Collections\**" />
    <PRIResource Remove="View\Descriptors\Filtering\DataEngineMapping\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="GlobalSuppressions.cs" />
    <Compile Remove="Model\DataChangeFlags.cs" />
    <Compile Remove="View\Descriptors\DataDescriptor.cs" />
    <Compile Remove="View\Descriptors\DelegateMemberAccess.cs" />
    <Compile Remove="View\Descriptors\Filtering\BooleanFilterDescriptor.cs" />
    <Compile Remove="View\Descriptors\Filtering\CompositeFilterDescriptor.cs" />
    <Compile Remove="View\Descriptors\Filtering\DataGridNestedPropertyTextFilterDescriptor.cs" />
    <Compile Remove="View\Descriptors\Filtering\DateTimeFilterDescriptor.cs" />
    <Compile Remove="View\Descriptors\Filtering\DateTimePart.cs" />
    <Compile Remove="View\Descriptors\Filtering\DelegateFilterDescriptor.cs" />
    <Compile Remove="View\Descriptors\Filtering\FilterDescriptorBase.cs" />
    <Compile Remove="View\Descriptors\Filtering\LogicalOperator.cs" />
    <Compile Remove="View\Descriptors\Filtering\NumericalFilterDescriptor.cs" />
    <Compile Remove="View\Descriptors\Filtering\NumericalOperator.cs" />
    <Compile Remove="View\Descriptors\Filtering\PropertyFilterDescriptor.cs" />
    <Compile Remove="View\Descriptors\Filtering\TextFilterDescriptor.cs" />
    <Compile Remove="View\Descriptors\Filtering\TextOperator.cs" />
    <Compile Remove="View\Descriptors\Grouping\DelegateGroupDescriptor.cs" />
    <Compile Remove="View\Descriptors\Grouping\GroupDescriptorBase.cs" />
    <Compile Remove="View\Descriptors\Grouping\PropertyGroupDescriptor.cs" />
    <Compile Remove="View\Descriptors\IKeyLookup.cs" />
    <Compile Remove="View\Descriptors\IPropertyDescriptor.cs" />
    <Compile Remove="View\Descriptors\NestedPropertyKeyLookup.cs" />
    <Compile Remove="View\Descriptors\OrderedDescriptor.cs" />
    <Compile Remove="View\Descriptors\Sorting\DelegateSortDescriptor.cs" />
    <Compile Remove="View\Descriptors\Sorting\PropertySortDescriptor.cs" />
    <Compile Remove="View\Descriptors\Sorting\SortDescriptorBase.cs" />
    <Compile Remove="View\Services\Updates\DelegateUpdate.cs" />
    <Compile Remove="View\Services\Updates\IUpdateService.cs" />
    <Compile Remove="View\Services\Updates\Update.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Assets\FilterFlyout\ic_clear.png" />
    <None Remove="Assets\FilterFlyout\ic_clear.scale-140.png" />
    <None Remove="Assets\FilterFlyout\ic_clear.scale-180.png" />
    <None Remove="Assets\FilterFlyout\ic_clear.scale-240.png" />
    <None Remove="Assets\FilterFlyout\ic_clear_black.png" />
    <None Remove="Assets\FilterFlyout\ic_clear_black.scale-140.png" />
    <None Remove="Assets\FilterFlyout\ic_clear_black.scale-180.png" />
    <None Remove="Assets\FilterFlyout\ic_clear_black.scale-240.png" />
    <None Remove="Assets\FilterFlyout\ic_clear_hover.png" />
    <None Remove="Assets\FilterFlyout\ic_clear_hover.scale-140.png" />
    <None Remove="Assets\FilterFlyout\ic_clear_hover.scale-180.png" />
    <None Remove="Assets\FilterFlyout\ic_clear_hover.scale-240.png" />
    <None Remove="Assets\FilterFlyout\ic_clear_white.png" />
    <None Remove="Assets\FilterFlyout\ic_clear_white.scale-140.png" />
    <None Remove="Assets\FilterFlyout\ic_clear_white.scale-180.png" />
    <None Remove="Assets\FilterFlyout\ic_clear_white.scale-240.png" />
    <None Remove="Assets\FilterFlyout\ic_filter_header_dark.png" />
    <None Remove="Assets\FilterFlyout\ic_filter_header_dark.scale-140.png" />
    <None Remove="Assets\FilterFlyout\ic_filter_header_dark.scale-180.png" />
    <None Remove="Assets\FilterFlyout\ic_filter_header_dark.scale-240.png" />
    <None Remove="Assets\FilterFlyout\ic_filter_header_light.png" />
    <None Remove="Assets\FilterFlyout\ic_filter_header_light.scale-140.png" />
    <None Remove="Assets\FilterFlyout\ic_filter_header_light.scale-180.png" />
    <None Remove="Assets\FilterFlyout\ic_filter_header_light.scale-240.png" />
    <None Remove="CustomDictionary.xml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core.UWP.NET9\Core.UWP.NET9.csproj" />
    <ProjectReference Include="..\..\Data.UWP.NET9\Data.UWP.NET9.csproj" />
    <ProjectReference Include="..\..\DataControls\DataControls.UWP.NET9\DataControls.UWP.NET9.csproj" />
    <ProjectReference Include="..\..\Input\Input.UWP.NET9\Input.UWP.NET9.csproj" />
    <ProjectReference Include="..\..\Primitives\Primives.UWP.NET9\Primitives.UWP.NET9.csproj" />
  </ItemGroup>
</Project>
