<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <Nullable>disable</Nullable>
    <UseUwp>true</UseUwp>
    <DefaultLanguage>en-US</DefaultLanguage>
    <IsAotCompatible>true</IsAotCompatible>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <AssemblyName>Telerik.Data</AssemblyName>
    <RootNamespace>Telerik.Data</RootNamespace>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\BuildTools\Win8PublicKey.snk</AssemblyOriginatorKeyFile>
    <Platforms>ARM64;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DefineConstants>$(DefineConstants);DEBUG;TRACE;NETFX_CORE;WINDOWS_UWP</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DefineConstants>$(DefineConstants);TRACE;NETFX_CORE;WINDOWS_UWP</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Data\Engine\Layouts\**" />
    <EmbeddedResource Remove="Data\Engine\Layouts\**" />
    <None Remove="Data\Engine\Layouts\**" />
    <Page Remove="Data\Engine\Layouts\**" />
    <PRIResource Remove="Data\Engine\Layouts\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Data\Descriptors\DataDescriptorBase.cs" />
    <Compile Remove="Data\Descriptors\Filtering\DataGridUserFilterMode.cs" />
    <Compile Remove="Data\Descriptors\IDataDescriptor.cs" />
    <Compile Remove="Data\Descriptors\Sorting\DataGridUserSortMode.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core.UWP.NET9\Core.UWP.NET9.csproj" />
  </ItemGroup>
</Project>
